version: "3"

services:
  py-loader:
    image: corgiai.azurecr.io/corgiai/py-loader:latest
    networks:
      - corgi-net
    ports:
      - 8081:8080
      - 8100:8100
    volumes:
      - ./data/embedding_model:/embedding_model

  py-chat:
    image: corgiai.azurecr.io/corgiai/py-chat:latest
    networks:
      - corgi-net
    ports:
      - 8200:8200
    volumes:
      - ./data/embedding_model:/embedding_model

  app:
    image: corgiai.azurecr.io/corgiai/app:latest
    networks:
      - corgi-net
    ports:
      - 8080:8080

networks:
  corgi-net: