services:
  py-loader:
    build:
      context: ./apps/py-loader
    networks:
      - corgi-net
    ports:
      - 8100:8100
    volumes:
      - ./data/embedding_model:/embedding_model
    depends_on:
      neo:
        condition: service_healthy
    x-develop: # x here is important for some reason
      watch:
        - action: rebuild
          path: ./apps/py-loader
      
  neo:
    image: neo4j:5.11
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - ./data/neo:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
        interval: 5s
        timeout: 3s
        retries: 5
    networks:
      - corgi-net

networks:
  corgi-net: