version: "3"

services:
  llm:
    image: ollama/ollama:latest
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - corgi-net

  neo:
    image: neo4j:5.13
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - ./data/neo:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME-neo4j}/${NEO4J_PASSWORD-password}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
        interval: 5s
        timeout: 3s
        retries: 5
    networks:
      - corgi-net

  py-loader:
    image: corgiai.azurecr.io/corgiai/py-loader:latest
    networks:
      - corgi-net
    ports:
      - 8081:8080
      - 8100:8100
    volumes:
      - ./data/embedding_model:/embedding_model

  py-chat:
    image: corgiai.azurecr.io/corgiai/py-chat:latest
    networks:
      - corgi-net
    ports:
      - 8200:8200
    volumes:
      - ./data/embedding_model:/embedding_model
  
  pull-model:
    image: corgiai.azurecr.io/corgiai/pull-model:latest
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
      - LLM=${LLM-llama2}
    networks:
      - corgi-net

  app:
    image: corgiai.azurecr.io/corgiai/app:latest
    networks:
      - corgi-net
    ports:
      - 8080:8080

networks:
  corgi-net: